Iter13
rawen554/shortener pull request #13
Opened 2023-06-13 23:18 UTC by rawen554

2023-06-16 16:45 UTC, s-shpak requested changes

2023-06-16 16:45 UTC, s-shpak commented on cmd/shortener/main.go
> +		storage.Get = s.Get
Так не стоит делать, возвращай готовый к использованию объект из конструктора (здесь придется использовать интерфейсы). Объект, по сути, у тебя уже и так готов, т.к. ты переприсваиваешь методы GenericStore. Сделай GenericStore интерфейсом, и все получится

2023-06-16 16:45 UTC, s-shpak commented on internal/app/app.go
> +	result, err := a.store.GetBatch(batch)
Возвращай лучше результаты прямо из `PutBatch`

2023-06-16 16:45 UTC, s-shpak commented on internal/app/app.go
> +	json.NewEncoder(res).Encode(result)
Здесь ошибку надо проверить

2023-06-16 16:45 UTC, s-shpak commented on internal/app/app.go
> +				id, err = a.store.GetByURL(originalURL)
Здесь не обязательно делать второй запрос: можно использовать`ON CONFLICT` в SQL-запросе в `store.Put`

2023-06-16 16:45 UTC, s-shpak commented on internal/app/app.go
> +	db, err := sql.Open("pgx", a.config.DatabaseDSN)
Не стоит каждый раз открывать новое соединение к БД, используй одно и то же (которое ты также будешь использовать в остальных хендлерах) - соединения к БД долгоживущие

2023-06-16 16:45 UTC, s-shpak commented on internal/store/dbstore.go
> +	db.ExecContext(context.Background(), `CREATE UNIQUE INDEX url_idx ON shortener (url)`)
Можно не создавать индекс отдельно, а сразу задать его при создании таблицы

2023-06-16 16:45 UTC, s-shpak commented on internal/store/dbstore.go
> +	*sql.DB
Лучше не встраивать это поле в структуру: мы не хотим, чтобы вышележащие слои могли посылать запросы к БД напрямую

2023-06-16 16:45 UTC, s-shpak commented on internal/store/dbstore.go
> +		_, err := tx.ExecContext(context.Background(), "INSERT INTO shortener VALUES ($1, $2)", url.CorrelationID, url.OriginalURL)
Это не настоящий батчинг: необходимо делать только один запрос к БД и посылать все разом. Я рекоммендую для этого уйти от `db/sql` и использовать `pgx`. Если ты все же хочешь использовать `db/sql`, посмотри в сторону библиотек, которые упрощают написание запросов (https://github.com/Masterminds/squirrel или https://github.com/jmoiron/sqlx)

2023-06-16 16:45 UTC, s-shpak commented on internal/store/dbstore.go
> +func (db *DBStore) GetBatch(batch []BatchReq) ([]BatchRes, error) {
См. комментарий к `PutBatch`

2023-06-16 16:45 UTC, s-shpak commented on internal/store/dbstore.go
> +func (db *DBStore) DropTable() error {
А это зачем?

2023-06-19 07:56 UTC, rawen554 commented on internal/store/dbstore.go
> +func (db *DBStore) DropTable() error {
Думал для тестов, чтобы чистить.
Хотя наверно правильно все же мокать, иначе это уже будут интеграционные тесты.

2023-06-20 14:14 UTC, s-shpak commented on internal/store/postgres/store.go
> +		"id VARCHAR(255) NOT NULL, "+
`id` тоже же должен быть уникальным?

2023-06-20 14:14 UTC, s-shpak commented on internal/store/postgres/store.go
> +	conn *pgx.Conn
Используй `pgxpool`, `pgx.Conn` неконкуренто безопасно

2023-06-20 14:14 UTC, s-shpak commented on internal/store/dbstore.go
> +func (db *DBStore) DropTable() error {
Можно писать и интеграционные тесты, но тогда как правило уничтожением БД для тестов занимается не код, а какая-то внешняя сущность. В основной функционал сервиса не должна попадать логика, которая предназначена только для тестов.

2023-06-20 14:18 UTC, s-shpak requested changes

2023-06-20 14:18 UTC, s-shpak commented on internal/app/app.go
> +	storeType := reflect.TypeOf(a.store)
Не стоит использовать рефлексию. Просто помести `Ping` в интерфейс стора, и в случае `fs` и `memory` просто возвращай `nil` вместо ошибки

2023-06-22 18:31 UTC, s-shpak requested changes

2023-06-22 18:31 UTC, s-shpak commented on internal/store/postgres/store.go
> +	conn, err := pgxpool.New(context.Background(), dsn)
Контекст должне приходить извне (часто это контекст запроса), но можно сделать в следующем спринте - тогда просто зарезолвь этот коммент и отправь еще раз на ревью

2023-06-23 08:46 UTC, s-shpak approved these changes

2023-06-25 03:50 UTC, merged