Iter15
rawen554/shortener pull request #15
Opened 2023-06-27 14:15 UTC by rawen554

2023-06-29 18:33 UTC, s-shpak requested changes

2023-06-29 18:33 UTC, s-shpak commented on cmd/shortener/main.go
> +	r.Use(ginLoggerMiddleware)
Почему ты поменял последовательность вызовов `middleware`?

2023-06-29 18:33 UTC, s-shpak commented on internal/app/app.go
> +func (a *App) GetUserRecors(c *gin.Context) {
```suggestion
func (a *App) GetUserRecords(c *gin.Context) {
```

2023-06-29 18:33 UTC, s-shpak commented on internal/auth/auth.go
> +const SecretKey = "b4952c3809196592c026529df00774e46bfb5be0"
Я понимаю, что этого не было в ТЗ, но было бы лучше, если бы можно было передавать ключ серверу при запуске

2023-06-29 18:33 UTC, s-shpak commented on internal/store/memory/store.go
> +	return nil, nil
Логику следует реализовать и для этой имлементации

2023-06-29 18:33 UTC, s-shpak commented on internal/app/app.go
> +	go func() {
1. Запросов к БД может быть очень много, что может положить БД. Как это можно справить на уровне Pool'а соединений?
2. Как можно добавить graceful shutdown к этому? (Это не обязательно, т.к. в ТЗ нет, но если есть желание, то было бы здорово сделать)

2023-06-29 22:32 UTC, rawen554 commented on cmd/shortener/main.go
> +	r.Use(ginLoggerMiddleware)
Дебажил ошибку.
Получается, в порядке вызовов обертка происходит? Правильнее первым middleware указывать logger -> gzip -> auth?
Логика такая, поправь, если не так:
logger первым чтобы записывать все запросы, если какая то MW встанет перед ним и завершиться через return с записью заголовка например, то и до следующих MW дело не дойдет?
Или gzip, чтобы сперва подменить http.ResponseWriter и io.ReadCloser?

2023-07-03 13:34 UTC, rawen554 commented on internal/app/app.go
> +	go func() {
1) Я думаю так - pgxpool конкуррентнобезопасен, у него есть MaxConns := runtime.NumCPU(), в рамках которых он будет обращаться к базе, причем под капотом производится HealthCheck базы.
Возможно стоит внедрить debounce задержку перед обращением к базе, с помощью горутин и каналов.
2) Интересно, постараюсь сделать.

2023-07-04 11:40 UTC, s-shpak commented on cmd/shortener/main.go
> +	r.Use(ginLoggerMiddleware)
Вызов middleware как матрешка:

```go
r.Use(middleware1)
r.Use(middleware2)
```

Приводит к такой оследовательности событий:

```go
middleware1PreHandlingLogic()
middleware2PreHandlingLogic()

handlerRequest()

middleware2PostHandlingLogic()
middleware1PostHandlingLogic()
```

Я бы определил последовательность так: логгер - аутентификатор - gzip

2023-07-04 11:42 UTC, s-shpak commented on internal/app/app.go
> +	go func() {
В идеале `maxConns` можно было бы сделать конфигурируемым, но, в принципе, достаточно его захардкодить на данный момент. Только я советовал бы выставлять его явно, чтобы было понятно, какое количество соединений может быть открыто (оно может быть и больше NumCPU, кстати, как думаешь, почему)?

2023-07-04 12:16 UTC, rawen554 commented on internal/app/app.go
> +	go func() {
Возможно, если его захардкодить, это может приводить к исскуственному троттлингу, слишком большое количество соединений тоже должно быть обосновано, иначе приведет к нерациональному использованию ресурсов.
+ надо еще посмотреть какой параметр выставлен в конфигурации самой базы.
Провести нагрузочные тесты и посравнивать результат.

2023-07-04 14:16 UTC, rawen554 commented on internal/app/app.go
> +	go func() {
Поправлю себя, не совсем так, мы ведь настраиваем максимальное количество соединений. Вот как раз таки, если оставить его дефолтным - это может приводить к троттлингу на уровне приложения, а база может быть недонагружена.
Но замечание по поводу live тюнинга и поиска предельного параметра, после которого возможна деградация производительности - оставлю без изменения.

2023-07-05 09:29 UTC, s-shpak approved these changes

2023-07-05 11:34 UTC, merged