Iter23
rawen554/shortener pull request #19
Opened 2023-09-27 09:19 UTC by rawen554

2023-09-28 07:55 UTC, s-shpak commented on cmd/shortener/main.go
> +				errs <- fmt.Errorf("error creating tls certs: %w", err)
Я бы добавил return

2023-09-28 08:19 UTC, s-shpak requested changes

2023-09-28 08:19 UTC, s-shpak commented on internal/app/tls.go
> +		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth},
Зачем здесь `x509.ExtKeyUsageClientAuth` ?

2023-09-28 08:19 UTC, s-shpak commented on internal/app/tls.go
> +		logger.Fatal(err)
Не надо здесь фаталиться нигде

2023-09-28 08:19 UTC, s-shpak commented on internal/config/config.go
> +		if err := mergo.Merge(&config, configFromFile); err != nil {
Напиши, пожалуйста, тесты

2023-09-28 08:19 UTC, s-shpak commented on internal/app/tls.go
> +	certFile, err := os.OpenFile("./certs/cert.pem", os.O_WRONLY|os.O_CREATE, CertsPerm)
Разбей генерацию сертификатов и запись на два компонента

2023-09-28 08:19 UTC, s-shpak commented on internal/config/config.go
> +	flag.BoolVar(&config.EnableHTTPS, "s", false, "enable https")
По умолчанию лучше `true`

2023-09-28 08:19 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&config.Secret, "e", "b4952c3809196592c026529df00774e46bfb5be0", "Secret")
JWT-проверки

2023-09-29 13:27 UTC, rawen554 commented on internal/config/config.go
> +	flag.BoolVar(&config.EnableHTTPS, "s", false, "enable https")
Если `true` то все тесты начинают валиться. Надо делать редирект на `https`.

2023-09-29 19:00 UTC, s-shpak approved these changes

2023-10-01 12:28 UTC, merged