Iter25
rawen554/shortener pull request #20
Opened 2023-10-10 09:34 UTC by rawen554

2023-10-11 15:02 UTC, s-shpak requested changes

2023-10-11 15:02 UTC, s-shpak commented on cmd/shortener/main.go
> +				logger.Fatal("failed to listen:", zap.Error(err))
Не надо фаталиться внутри горутины

2023-10-11 15:02 UTC, s-shpak commented on cmd/staticlint/internal/osexitchecker/osexitchecker.go
> +var mainName = "main"
Если это из-за линтера, то лучше

```suggestion
const mainName = "main"
```

2023-10-11 15:02 UTC, s-shpak commented on internal/middleware/auth/subnet.go
> +			logger.Errorf("internal request: unauthorized request denied: ip %s", ipAddr.String())
```suggestion
			logger.Errorf("internal request: unauthorized request denied: ip %s", ipAddr)
```

2023-10-11 15:02 UTC, s-shpak commented on internal/proto/shortener.proto
1. Добавь, пожалуйста, комментарии к структурам здесь - они будут перенесены в код
2. Сгенерированные файлы лучше помещать отдельно от `.proto` файлов, лучше в тот пакет, который их использует
3. Имя пакета, соответственно, надо выставлять корректно, посмотри как это делается в документации

2023-10-11 15:02 UTC, s-shpak commented on internal/store/memory/store.go
> +	return nil, fmt.Errorf("not implemented")
Есть ли какая-то принципиальная проблема с добавлением неободимой логики сюда?

2023-10-11 15:03 UTC, rawen554 commented on internal/store/memory/store.go
> +	return nil, fmt.Errorf("not implemented")
Нет, не заметил, забыл добавить.

2023-10-13 08:46 UTC, s-shpak approved these changes

2023-10-13 09:08 UTC, merged