Iter5
rawen554/shortener pull request #5
Opened 2023-05-06 21:45 UTC by rawen554

2023-05-08 16:14 UTC, s-shpak requested changes

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/flags.go
> +	flag.StringVar(&config.RedirectBaseURL, "b", "http://localhost:8080", "server uri prefix")
`uri` -- аббревиатура, ее стоит писать заглавными буквами

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/flags.go
> +		log.Fatal(err)
Это касается не только этой ошибки, но обработки ошибок в целом (надо поправить и в других местах).

Обычно в Go критические ошибки (которые не позволяют продолжить выполнение программы) возвращаются из функции и доходят до самого верхнего уровня (до функции main или, если речь идет об отдельной горутине, до функции которая была в ней запущена), где они логируются, и программа завершается.

Не стоит выходить из программы где-то в глубине логики:
- Код сложнее читать, лучше, когда понятно, где именно точка выхода
- Не получится завершить сторонние процессы штатным образом, что может привести к проблемам

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +func setupRouter(ptrUrls *map[string][]byte) *gin.Engine {
1. Мапы в Go (как и функции и слайсы) практически никогда не передаются через указатель (т.к. сами, по сути, почти голый указатель). Добавление элементов в мапу не создает новую мапу, потому указатель в данном случае не нужен
2. В Go в имена переменных не принято записывать информацию о типе. Тем более это справедливо для указателей, т.к. работа с ними часто полностью прозрачная для программиста

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +		defer req.Body.Close()
Закрывать тело реквеста не обязательно: см. документацию к полю `Body` в https://pkg.go.dev/net/http#Request

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +		res.Write([]byte(config.RedirectBaseURL + "/" + id))
Для формирования URL лучше использовать https://pkg.go.dev/net/url#JoinPath

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +	"crypto/rand"
Для данного use-case нам достаточно использовать `math/rand`: он более производителен, чем `crypto/rand`, а дополнительные гарантии, которые дает криптографически стойкий генератор случайных чисел, нам не требуются

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +		num, err := rand.Int(rand.Reader, big.NewInt(int64(len(letters))))
В случае с `math/rand` можно будет использовать `Intn`

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
> +func GenerateRandomString(n int) (string, error) {
Эту функцию необязательно делать экспортируемой

2023-05-08 16:14 UTC, s-shpak commented on go.mod
У тебя устарел `go.mod`, обнови его с помощью `go mod tidy`

2023-05-08 16:14 UTC, s-shpak commented on cmd/shortener/main.go
Мне не очень нравится структура проекта: в `cmd` в идеале должна лежать только логика, позволяющая запустить твой сервис, все прочее должно лежать в `internal`. Перенеси, пожалуйста, логику туда

2023-05-11 16:58 UTC, s-shpak requested changes

2023-05-11 16:58 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Не стоит паниковать, используй лучше `log.Fatal`

2023-05-11 16:58 UTC, s-shpak commented on cmd/shortener/main.go
> +	err := flags.ParseFlags()
`err` лучше обернуть в `if`: так новая переменная не будет влиять на внешнюю область видимости

2023-05-11 16:58 UTC, s-shpak commented on cmd/shortener/main_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `tt := tt`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-11 16:58 UTC, s-shpak commented on internal/handlers/handlers.go
> +		originalURL := urls[id]
На твое усмотрение: сейчас у нас возникнут проблемы, если одновременно писать в мапу и читать из нее, если чувствуешь в себе силы, попробуй исправить это

2023-05-11 16:58 UTC, s-shpak commented on internal/handlers/handlers.go
> +			panic(err)
Не надо паниковать в глубине кода, отправь ошибку пользователю и завершись штатно. Если будешь отправлять ошибку `InternalServerError` не передавай ползьователю информацию о том, что именно произошло: это небезопасно

2023-05-11 16:58 UTC, s-shpak commented on internal/handlers/handlers.go
> +			panic(err)
Аналогично

2023-05-11 16:58 UTC, s-shpak commented on internal/handlers/handlers.go
> +			panic(err)
Аналогично

2023-05-15 12:24 UTC, s-shpak requested changes

2023-05-15 12:24 UTC, s-shpak commented on internal/handlers/handlers.go
> +func NewSyncURLMap(urls map[string][]byte) SyncURLMap {
Я понимаю, что ты передаешь `urls` здесь для тестов, но это не очень логично в коде. Сделай лучше так: создай дополнительную структуру `store`, для которой ты можешь определить два метода `Put` и `Get`. Это решит и проблему тестирования, и позволит нормально ее инициализировать

2023-05-15 12:24 UTC, s-shpak commented on internal/handlers/handlers.go
> +func RedirectToOriginal(m SyncURLMap) func(c *gin.Context) {
Через замыкания это делать нормально, но я рекомендовал бы все же использовать методы

2023-05-15 12:24 UTC, s-shpak commented on internal/utils/utils.go
> +	if n < 0 {
А имеет ли смысл принимать `n == 0` ?

2023-05-15 12:24 UTC, s-shpak commented on internal/utils/utils.go
> +		return "", errors.New("negative length")
Я бы логировал значение, которое привело к ошибке (`fmt.Errorf`)

2023-05-16 23:24 UTC, s-shpak requested changes

2023-05-16 23:24 UTC, s-shpak commented on cmd/shortener/main.go
> +	app := app.NewApp(config, store.NewStorage(make(map[string][]byte)))
Этому коду не нужно знать, как организован `storage`, инициализируй мапу в его конструкторе

2023-05-16 23:24 UTC, s-shpak commented on internal/app/app.go
> +		res.WriteHeader(http.StatusInternalServerError)
`InternalServerError` лучше логировать, т.к. это позволит понять какая непредвиденная ошибка произошла

2023-05-16 23:24 UTC, s-shpak commented on internal/store/store.go
> +	s.mux.Unlock()
`Unlock` лучше вызывать в `defer` после строки 18

2023-05-16 23:24 UTC, s-shpak commented on internal/store/store.go
> +	s.mux.Unlock()
`Unlock` лучше вызывать в `defer` после строки 24

2023-05-17 05:45 UTC, rawen554 commented on cmd/shortener/main.go
> +	app := app.NewApp(config, store.NewStorage(make(map[string][]byte)))
Тогда не понимаю, как тестировать метод получения url из мапы. Ведь мне эту мапу надо будет предварительно наполнить.

2023-05-17 06:18 UTC, rawen554 commented on cmd/shortener/main.go
> +	app := app.NewApp(config, store.NewStorage(make(map[string][]byte)))
Вроде разобрался.

2023-05-17 08:03 UTC, s-shpak requested changes

2023-05-17 08:03 UTC, s-shpak commented on internal/app/app.go
> +		fmt.Printf("body cannot be read: %s\n", err)
Логирование лучше делать через библиотеку `log`, для первого спринта этого достаточно:

```suggestion
		log.Printf("body cannot be read: %v", err)
```

2023-05-17 08:03 UTC, s-shpak commented on internal/app/app.go
> +		fmt.Printf("random string generator error: %s\n", err)
```suggestion
		log.Printf("random string generator error: %v", err)
```

2023-05-17 08:03 UTC, s-shpak commented on internal/app/app.go
> +		fmt.Printf("URL cannot be joined: %s\n", err)
```suggestion
		log.Printf("URL cannot be joined: %v", err)
```

2023-05-17 08:06 UTC, s-shpak requested changes

2023-05-17 08:06 UTC, s-shpak commented on internal/app/app.go
> +	res.Write([]byte(result))
Попробуй привыкнуть на автомате либо обрабатывать ошибки, если функция их возвращает, либо явно игнорить (через `_ = res.Write([]byte(result))`, если ты знаешь, что тебе не нужно знать о том, что ошибка произошла (в подавляющем большинстве случаев это неверный подход).

Здесь ошибку можно обработать по-разному, пока достаточно ее залогировать

2023-05-17 08:46 UTC, s-shpak approved these changes
LGTM!

2023-05-17 08:58 UTC, merged