Iter9
rawen554/shortener pull request #9
Opened 2023-05-30 01:46 UTC by rawen554

2023-06-04 09:35 UTC, s-shpak requested changes

2023-06-04 09:35 UTC, s-shpak commented on internal/.DS_Store
Этот файл надо убрать из репозитория и добавить в .gitignore

2023-06-04 09:35 UTC, s-shpak commented on .DS_Store
См. коммент к другому `.DS_Store`

2023-06-04 09:35 UTC, s-shpak commented on go.mod
Необходимо обновить при помощи `go mod tidy`

2023-06-04 09:35 UTC, s-shpak commented on cmd/shortener/main_test.go
> +	App "github.com/rawen554/shortener/internal/app"
здесь нет смысла переопределять имя пакета + имена пакетов не начинаются с заглавных букв

2023-06-04 09:35 UTC, s-shpak commented on cmd/shortener/main_test.go
> +				panic(err)
не надо паниковать даже в тестах: лучше:

```suggestion
				t.Errorf("failed to initialize a new storage: %v", err)
				return
```

2023-06-04 09:35 UTC, s-shpak commented on internal/compress/compress.go
> +func (c *compressWriter) Header() http.Header {
Если ты выстроишь `gin.ResponseWriter` в `compressWriter`, то тебе не придется явно определять методы, требуемые интерфейсом:

```go
type compressWriter struct {
	gin.ResponseWriter
	zw *gzip.Writer
}
```

2023-06-04 09:35 UTC, s-shpak commented on internal/logger/logger.go
> +		panic(err)
Не надо паниковать

2023-06-04 09:35 UTC, s-shpak commented on internal/logger/logger.go
> +		c.Next()
Таймер лучше стартовать непосредственно перед вызовом хендлера

2023-06-04 09:35 UTC, s-shpak commented on internal/store/store.go
> +			log.Fatal(err)
Не надо выходить из программы в глубине кода

2023-06-05 18:41 UTC, s-shpak requested changes

2023-06-05 18:41 UTC, s-shpak commented on .DS_Store
Этот файл тоже стоит убрать из репозитория

2023-06-05 18:41 UTC, s-shpak commented on internal/compress/compress.go
> +func (c *compressWriter) Write(p []byte) (int, error) {
Мне кажется, что раньше был еще Content-Length, если это так, то добавь его в эту реализацию, пожалуйста

2023-06-05 18:41 UTC, s-shpak commented on internal/store/store.go
> +		panic(err)
не надо паниковать

2023-06-05 18:41 UTC, s-shpak commented on internal/store/store.go
> +	s.sw.AppendToFile(&Record{UUID: strconv.Itoa(len(s.urls)), OriginalURL: url, ShortURL: id})
Здесь потенциально может быть небольшая проблема, если будут возникать коллизии (тогда uuid может начать повторяться). Это необязательно, но я бы советовал просто держать дополнительный каунтер, который точно (практически) гарантировал бы, что id уникальные.

Это делать необязательно, т.к. эта реализация переходная на пути к использованию БД, если ты не захочешь это делать просто зарезолвь коммент

2023-06-05 20:39 UTC, rawen554 commented on internal/compress/compress.go
> +func (c *compressWriter) Write(p []byte) (int, error) {
На самом деле тут не было выставления "Content-Length", но добавил.

2023-06-05 21:01 UTC, s-shpak commented on .DS_Store
https://stackoverflow.com/questions/2047465/how-do-i-delete-a-file-from-a-git-repository

2023-06-05 21:04 UTC, s-shpak requested changes

2023-06-05 21:04 UTC, s-shpak commented on cmd/shortener/__debug_bin
Тоже надо убрать

2023-06-05 21:04 UTC, rawen554 commented on .DS_Store
Сори, сейчас точно все почищу.

2023-06-05 21:22 UTC, s-shpak approved these changes

2023-06-12 18:27 UTC, merged